function [Utangential,Uperpendicular] = sectionSpeed(SectionMidPoint,HingeOffset,Radius,RotorSpeed, u,v,w, p,q,r, Azimuth, inflow, Beta,BetaD)
%[normalized][normalized][m][rad/s][3 x m/s][3 x rad/s][rad][m/s][rad][rad/s]
distElement2FlapHinge = (SectionMidPoint - HingeOffset) * Radius;
distElement2RotationCenter = SectionMidPoint * Radius;

RotationDirection = 1.0; %(-1:CCW, 1:CW)

Utangential     =   RotorSpeed * distElement2RotationCenter ...
                    + u * sin(Azimuth) ...
                    + v * cos(Azimuth) ...
                    + RotationDirection * r * distElement2RotationCenter ...
                    ;
                
Uperpendicular  =   -w ...
                    + inflow ...
                    + distElement2FlapHinge * BetaD ...
                    + u * cos(Azimuth) * sin(Beta) ...
                    + v * sin(Azimuth) * sin(Beta) ...
                    + q * cos(Azimuth) * distElement2RotationCenter ...
                    + RotationDirection * (+1.0) * p * sin(Azimuth) * distElement2RotationCenter ...
                    ;
end

